# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Alex-gitss"
repo_name: "mas-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Multi-Agent Reinforcement Learning":
        filters: ["Multi-Agent Reinforcement Learning", "MARL", "Multi-agent RL", 
                  "Cooperative Reinforcement Learning", "Competitive Reinforcement Learning"]
    "Multi-Agent Systems":
        filters: ["Multi-Agent System", "Multi-agent System", "MAS", 
                  "Distributed AI", "Distributed Artificial Intelligence"]
    "Multi-Agent Coordination":
        filters: ["Multi-Agent Coordination", "Agent Coordination", 
                  "Multi-Agent Planning", "Cooperative Planning", 
                  "Distributed Planning", "Multi-Agent Task Assignment"]
    "Multi-Agent Communication":
        filters: ["Multi-Agent Communication", "Agent Communication", 
                  "Communication Protocol", "Message Passing", 
                  "Emergent Communication"]
    "Game Theory and MAS":
        filters: ["Game Theory", "Nash Equilibrium", "Mechanism Design", 
                  "Auction Theory", "Cooperative Game Theory", "Multi-Agent Game"]
    "Swarm Intelligence":
        filters: ["Swarm Intelligence", "Collective Intelligence", 
                  "Emergent Behavior", "Self-Organization", "Ant Colony Optimization"]
    "Consensus and Agreement":
        filters: ["Consensus Algorithm", "Distributed Consensus", 
                  "Byzantine Agreement", "Fault Tolerance", "Agreement Protocol"]
    "Multi-Agent Simulation":
        filters: ["Agent-Based Modeling", "Multi-Agent Simulation", 
                  "ABM", "Agent-Based Model", "Complex Adaptive Systems"]
